### ISSUE TITLE
[Feature]: GetAllAsync method with filter possibilities in the application storage

### ISSUE THREAD

**Issue by tsudd** [dotnet-essentials/Kwality.UVault#18]
### Background and motivation

**Problem**
Right now, existing `GetAllAsync` method doesn't allow to return specific applications from the storage. It accepts only page number and page size, which is really limited. The goal of this request is to create an additional method which will allow to pass a request object with filter details to perform more specific request of applications.

**Solution**
Create an additional method, which will allow to specify filter details for any storage, for instance which fields to fetch from the storage, which objects to exclude etc.

### How urgent do you need this feature?

It's an urgent deal-breaker. I can't live without it.

### Proposed API

Lets create an overload of the existing `GetAllAsync` method, which will allow to pass pageIndex, pageSize and `IApplicationOperationMapper` instance. It will be used by custom storage to apply specific filters and details for a query.
Expected result to have a method with the next signature:
```c#
Task<PagedResultSet<TModel>> GetAllAsync(int pageIndex, int pageSize, IApplicationOperationMapper mapper);
```

### Acceptance criteria

- New method, which allows custom filtering, is implemented in the API
- New functionality is covered with tests

**Comment by kdeconinck** [comment]
An `IApplicationOperationMapper` maps an input to a certain output.
So using this interface isn't supported for filtering out all data.

However, I will create a different approach to apply filtering.
